Repository MUTUAL-DE-SERVICIOS-AL-POLICIA/Login-Hub-Interface, pull requests merged in 2025-04, with the labels that each got.

#19 REFACTORIZACIÓN DE CONFIGURACIÓN PARA LOGIN LOGOUT, COOKIES Y PETICIONES API
  .env.example
  src/api/auth/login.ts
  src/api/auth/logout.ts
  src/api/index.ts
  src/app/api/login/route.ts
  src/app/api/logout/route.ts
  src/app/login/page.tsx
  src/components/user.tsx
  src/middleware.ts
  src/services/APIConnection.ts
  src/services/FetchServiceFactory.ts
Labels: enhancement

#20 resolviendo problema para que la cookie sea de difrente dominio al lo…
  src/api/index.ts
  src/app/api/route.ts
  src/app/login/page.tsx
  src/services/FetchServiceFactory.ts
Labels: bug

#21 redirección bug
  src/app/login/page.tsx
Labels: bug

#22 ajuste de logo tamaño
  public/Formulario_610v4.pdf
  src/components/icons.tsx
  src/components/navbar.tsx
Labels: bug

#24 Refactorizacion de Apphub leyendo los modulos por Cookie
  public/beneficiary.jpg
  public/mod0.jpg
  public/mod1.jpg
  src/api/auth/logout.ts
  src/app/api/route.ts
  src/app/apphub/page.tsx
  src/components/icons.tsx
  src/components/navbar.tsx
  src/components/software.tsx
  src/components/user.tsx
  src/config/site.ts
  src/helpers/cookies.ts
  src/helpers/interfaces.ts
Labels: enhancement

#26 Se arreglo la lectura de las url del modulo desde la cookie
  src/app/apphub/page.tsx
  src/components/software.tsx
  src/helpers/interfaces.ts
Labels: bug, enhancement

#28 REFACTORIZACION DE ESTRUCTURA Y LEER USUARIO DESDE LA COOKIE
  src/api/auth/logout.ts
  src/app/api/route.ts
  src/app/apphub/layout.tsx
  src/app/apphub/page.tsx
  src/app/layout.tsx
  src/app/login/layout.tsx
  src/app/login/page.tsx
  src/components/apphub/software.tsx
  src/components/common/icons.tsx
  src/components/common/index.ts
  src/components/common/primitives.ts
  src/components/common/theme-switch.tsx
  src/components/header/navbar.tsx
  src/components/header/user.tsx
  src/components/navbar.tsx
  src/helpers/cookies.ts
  src/helpers/interfaces.ts
  src/utils/context/AlertProvider.tsx
  src/utils/fonts.ts
  src/utils/helpers/cookies.ts
  src/utils/hooks/useAlerts.tsx
  src/utils/interfaces/index.ts
  src/utils/services/APIConnection.ts
  src/utils/services/APIConnectionFactory.ts
  src/utils/services/FetchService.ts
  src/utils/services/FetchServiceFactory.ts
  src/utils/services/index.ts
  src/utils/styles/globals.css
  src/utils/types/index.ts
Labels: enhancement

#30 Actualización de redirección
  src/components/software.tsx
  src/config/site.ts
Labels: enhancement
